gitのhookのctagsでExuberant Ctagsがあるかをチェックするようにした

diff --git a/home/.git_template/hooks/ctags b/home/.git_template/hooks/ctags
--- a/home/.git_template/hooks/ctags
+++ b/home/.git_template/hooks/ctags
@@ -1,9 +1,12 @@
 #!/usr/bin/env bash
 set -e
 PATH="$HOME/local/bin:/usr/local/bin:$PATH"
-if ! type ctags 1>/dev/null 2>&1; then
-    exit
+
+if ! ctags --version | grep 'Exuberant Ctags' 1>/dev/null 2>&1; then
+    echo 'ctags is not found'
+    exit 1
 fi
+
 cd "$(dirname "${BASH_SOURCE:-$0}")"; cd ../../
 trap "rm -f .git/tags.$$" EXIT
 ctags --tag-relative -R -f .git/tags.$$ --exclude=.git
